### PR TITLE
fix for setup.py

### PR DESCRIPTION
**Pull request by imec-myhdl**
Hi, 
When making a proper setup I made a wheel (python setup.py bdist_wheel) but that did not install the package hdlConvertor/hdlAst, so I added it to the setup.py file.

please ignore the readme.md github immediately commits changes, and i first tried to indicate that this was not the original.

Kind regards, Paul

### CODE REVIEW

**Comment by Nic30** [comment]
You are right, hdlConvertor package is not included recursively, I think there was an setup() argument to do so. But exact path for a single sub-package is enough. I would vote to use '.' instead of '/' for python package. But it seems to be working. I will will ensure that the packaging is fully working on all platforms before release.

Thanks for your contribution.

**Comment by Nic30** [comment]
Also talking about distribution. The default pip (pip 18.1) in latest Ubuntu seems to be broken after today's update.
(https://github.com/pypa/pip/issues/6428)

**Comment by imec-myhdl** [comment]
Hi,

I do get errors when using command “pip3 install something” but that’s easily circumvented by changing the command to “python3 -m pip install something”. This ‘bug’ is actually existing for quite some time. But I am still on a much older pip version (if it ain’t broken don’t upgrade. You would be surprised how often we have encountered problems with super simple upgrades)

Kind regards, Paul

**Comment by martinda** [comment]
Hi. Is there a chat room or a mailing list for this project?

**Pull request merged**
