### PR TITLE
Sv

### PR DESCRIPTION
**Pull request by Thomasb81**

### CODE REVIEW

**Comment by Thomasb81** [comment]
Regression is failing on travis.
On python2.7 as far as I understand the log :
The unittest on travis seems to be incompatible with the decorator expectedFailure...
But that's something 

In tests/test_preproc.py I have :
```
    #`MACRO3 must have parentesis according to the SV specification.
    #Currently the code is not able to detect this issue
    @unittest.expectedFailure
    def test_2012_p642_il2(self):
```
Maybe the test need simply to be commented ...

On python 3.x it is a code compatible python2/python3 issue 

Thomas

**Comment by Nic30** [comment]
> expectedFailure
odd, it should work aslo under python2.7 https://docs.python.org/2/library/unittest.html but if it is only this single tests,... I can fix it

**Comment by Thomasb81** [comment]
Commenting the test does not help. My analyze is incorrect :(

By another hand on my system : ubuntu18.10 /gcc8.10 c16c1d455544d478aa6d28d3c648917547ce388b (without my pull request) failed to compile
/home/tom/prog/tmp/hdlConvertor/src/hdlObjects/statement.cpp: In member function ‘PyObject* Statement::toJson() const’:
/home/tom/prog/tmp/hdlConvertor/src/hdlObjects/statement.cpp:161:3: error: invalid static_cast from type ‘const std::vector<std::vector<Statement*>*>’ to type ‘bool’
   assert(sub_statements);
   ^~~~~~

If I temporary comment this line (because this issue doesn't talk to me yet) It compile, but any test crash with a core dump, the back trace show point your recent change for python2 and python3.

It is odd that travis is ok ...

**Comment by Thomasb81** [comment]
Python3 test are now running on travis except the one that test exception occurrence.

**Comment by Nic30** [comment]
@Thomasb81 sorry for the delay, I forgot the laptop in the office and I lost the weekend. As soon as I get some time I will look in to it, it seems to me just a minor problems with pats and null values caused by some non implemented function. 

```
self.assertTrue('Missmatch in number of argument macro declaration D (2) and macro usage (3)' in context.exception)
TypeError: argument of type 'src.hdlConvertor.parseException' is not iterable
```
also the format of the exception should be probably some kind of tuple or the exception message is wrong.

**Comment by Nic30** [comment]
re:

```
/home/tom/prog/tmp/hdlConvertor/src/hdlObjects/statement.cpp:161:3: error: invalid static_cast from type ‘const std::vector<std::vector<Statement*>*>’ to type ‘bool’
```
I did fixed it. But still not sure if cmake_args= ['-DCMAKE_BUILD_TYPE=Debug']
is enough to make assers work. How did you enabled them?

**Comment by Thomasb81** [comment]
I did not put anything more. Here it is an issue reported by gcc at compile
time.

For the exception in the test, It could be related to the string
conversion... because this issue only appear with python3.

Thomas

**Comment by Nic30** [comment]
But where is this error message?  I can not find it anywhere https://travis-ci.org/Nic30/hdlConvertor/jobs/516359550 there are only different errors. Does this error happen only on your machine? I remember that there was some problem with the int literals, the python3 supports _ as a separator and the python2.7 does not. Also there is a unicode/str difference.

**Comment by Thomasb81** [comment]
Yes the error on assert argument seems to occur only on my machine. I did
not find it on Travis log.

**Comment by Nic30** [comment]
> error on assert argument

It was my fault id did fixed it in a3aea7f3d308bb92a479f4fc6beed1ca3c21480a
However the fact that the asserts are disabled on travis does not make me happy.

**Comment by Thomasb81** [comment]
For the preprocessor test expecting to failed. It seems the unittest.TestResult() does not have a default addExpectedFailure method. 
While on my ubuntu there was one default method.

How can we update the pip cache ? May be there is an updated  unitest package available...

**Comment by Nic30** [comment]
> How can we update the pip cache ? May be there is an updated unittest package available...

You mean to add the unittest dep. to setup.py ? Or you mean `pip install unittest --upgrade` ?

**Comment by Thomasb81** [comment]
Tests are now fix, for python2.7 and python3. Only remaining issue is the compilation for windows.

**Comment by Nic30** [comment]
Excellent Tomas! Thank you.

**Pull request merged**
